### PR TITLE
feat: filter out none http url when adding new network

### PR DESCRIPTION
**Pull request by yqrashawn**
PORTAL-2896

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/helios/902)

### CODE REVIEW

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2896 dapp 添加网络 和 person sign 的一些问题](https://app.clickup.com/t/3719212/PORTAL-2896)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2955 fluent rc.18之后, 不可以导入助记词了](https://app.clickup.com/t/3719212/PORTAL-2955)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2913 Rinkeby网络下添加token，balance一直处于loading状态](https://app.clickup.com/t/3719212/PORTAL-2913)

**Review by zctocm — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/902)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yqrashawn)

**Pull request merged**
