### PR TITLE
fix: fix bugs

### PR DESCRIPTION
**Pull request by RickStormBringer**
1.PORTAL-2790
2.PORTAL-2842
3.fit query-address

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/helios/866)

### CODE REVIEW

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2842 字体下载太慢 block 页面加载](https://app.clickup.com/t/3719212/PORTAL-2842)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2790 切换网络后报错](https://app.clickup.com/t/3719212/PORTAL-2790)

**Review by zctocm — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/866)* status: all files reviewed, 1 unresolved discussion (waiting on @RickStormBringer)

___
*[packages/popup/src/pages/Home/components/CurrentAccount.js, line 19 at r1](https://reviewable.io/reviews/conflux-chain/helios/866#-N-23JF25RzMw3Rz2DF3:-N-23JF37g1TZ5aEdKDi:b-2cffig) ([raw file](https://github.com/conflux-chain/helios/blob/915942662eaea65b7cbecf96ea8b6a2994300752/packages/popup/src/pages/Home/components/CurrentAccount.js#L19)):*
> ```JavaScript
> const OpenScanButton = ({address}) => {
>   const {t} = useTranslation()
>   const [jumpUrlStatus, setJumpUrlStatus] = useState('')
> ```

suggest that the default value `jumpUrlStatus` can be `false`

**Comment by RickStormBringer** [comment]
> > Reviewed 3 of 3 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/866)_ status: all files reviewed, 1 unresolved discussion (waiting on @RickStormBringer)
> 
> _[packages/popup/src/pages/Home/components/CurrentAccount.js, line 19 at r1](https://reviewable.io/reviews/conflux-chain/helios/866#-N-23JF25RzMw3Rz2DF3:-N-23JF37g1TZ5aEdKDi:b-2cffig) ([raw file](https://github.com/conflux-chain/helios/blob/915942662eaea65b7cbecf96ea8b6a2994300752/packages/popup/src/pages/Home/components/CurrentAccount.js#L19)):_
> 
> > ```js
> > const OpenScanButton = ({address}) => {
> >   const {t} = useTranslation()
> >   const [jumpUrlStatus, setJumpUrlStatus] = useState('')
> > ```
> 
> suggest that the default value `jumpUrlStatus` can be `false`

done

**Review by zctocm — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/866)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RickStormBringer)

___
*[packages/popup/src/pages/Home/components/CurrentAccount.js, line 19 at r1](https://reviewable.io/reviews/conflux-chain/helios/866#-N-23JF25RzMw3Rz2DF3:-N-5y_0e16x3vhg7bISa:bb6ywmx) ([raw file](https://github.com/conflux-chain/helios/blob/915942662eaea65b7cbecf96ea8b6a2994300752/packages/popup/src/pages/Home/components/CurrentAccount.js#L19)):*
<details><summary><i>Previously, RickStormBringer (Rick) wrote…</i></summary><blockquote>

done
</blockquote></details>

LGTM

**Pull request merged**
