### PR TITLE
fix: dup address->account issue

### PR DESCRIPTION
**Pull request by yqrashawn**
PORTAL-2560
PORTAL-2561
PORTAL-2772

# Breaking change in data structure

Mainly changed relation between account and address

Before:
- one account -> many addrs
- one addr -> one account
- addrs are component of account (del account result in deleting its addrs)
- get address/_account as single account obj

Now:
- many accounts -> many addrs
- many addrs ->  many accounts
- addrs only got deleted when there's no more linking accounts
- get address/_account as array of accounts
- need additional info when querying address account
- additional info can be
- appId (app has app's currentAccount's id)
- accountId
- selected: true (selected account's id)

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/helios/864)

### CODE REVIEW

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2561 不应该存在私钥相同的账户](https://app.clickup.com/t/3719212/PORTAL-2561)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2560 删除已有助记词里的account，会导致fluent回到重新设置密码页面](https://app.clickup.com/t/3719212/PORTAL-2560)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2772 删除账户后报错了](https://app.clickup.com/t/3719212/PORTAL-2772)

**Comment by RickStormBringer** [comment]
Hello.
    It looks like wallet_zeroAccountGroup  returns  an incorrect result. when i start project in branch fix/dup-creds.

**Comment by yqrashawn** [comment]
> Hello. It looks like wallet_zeroAccountGroup returns an incorrect result. When i start project in branch fix/dup-creds. Wallet goes to the unlock page even if I don't have an account.

@RickStormBringer I can't reproduce with the below steps.

1. checkout to origin/dev (6e4f52ad92fbb2bae338f455a6c295f9e1b3b430) run `yarn && yarn prod:shadow && yarn start`
2. install fluent
3. import a new seed
4. send a tx on cfx testnet
5. send a tx on cfx espace testnet
6. add mumbai testnet from chainlist
7. disable fluent
8. kill the prev `yarn start`
9. checkout to this pr (4fc9a490a5dfba03f469db0a2098609800b14ca8)
10. run `yarn && yarn prod:shadow && yarn start` again
11. enable fluent

**Comment by angelia-yuqi-personal** [comment]
> > Hello. It looks like wallet_zeroAccountGroup returns an incorrect result. When i start project in branch fix/dup-creds. Wallet goes to the unlock page even if I don't have an account.
> 
> @RickStormBringer I can't reproduce with the below steps.
> 
> 1. checkout to origin/dev ([6e4f52a](https://github.com/Conflux-Chain/helios/commit/6e4f52ad92fbb2bae338f455a6c295f9e1b3b430)) run `yarn && yarn prod:shadow && yarn start`
> 2. install fluent
> 3. import a new seed
> 4. send a tx on cfx testnet
> 5. send a tx on cfx espace testnet
> 6. add mumbai testnet from chainlist
> 7. disable fluent
> 8. kill the prev `yarn start`
> 9. checkout to this pr ([4fc9a49](https://github.com/Conflux-Chain/helios/commit/4fc9a490a5dfba03f469db0a2098609800b14ca8))
> 10. run `yarn && yarn prod:shadow && yarn start` again
> 11. enable fluent

I also reproduced with the below steps.

1. checkout fix/dup-creds
2. delete node_modules folder
3. run `yarn && yarn prod:shadow && yarn dev`
4. reload extension folder with Chrome
5. will display unlock page(should display welcome page with no account)

**Comment by zctocm** [comment]
> > Hello. It looks like wallet_zeroAccountGroup returns an incorrect result. When i start project in branch fix/dup-creds. Wallet goes to the unlock page even if I don't have an account.
> 
> @RickStormBringer I can't reproduce with the below steps.
> 
> 1. checkout to origin/dev ([6e4f52a](https://github.com/Conflux-Chain/helios/commit/6e4f52ad92fbb2bae338f455a6c295f9e1b3b430)) run `yarn && yarn prod:shadow && yarn start`
> 2. install fluent
> 3. import a new seed
> 4. send a tx on cfx testnet
> 5. send a tx on cfx espace testnet
> 6. add mumbai testnet from chainlist
> 7. disable fluent
> 8. kill the prev `yarn start`
> 9. checkout to this pr ([4fc9a49](https://github.com/Conflux-Chain/helios/commit/4fc9a490a5dfba03f469db0a2098609800b14ca8))
> 10. run `yarn && yarn prod:shadow && yarn start` again
> 11. enable fluent

The unlock page was displayed when I follow this process

**Comment by yqrashawn** [comment]
@angelia-yuqi-personal @RickStormBringer @zctocm 

I've fixed the zeroAccountGroup bug in the latest commit.
I can't reproduce that because I have a local setup script that create accounts for dev purpose on fluent start.

**Review by zctocm — CHANGES_REQUESTED** [review]
> Reviewed 54 of 54 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/864)* status: all files reviewed, 2 unresolved discussions (waiting on @angelia-yuqi-personal, @RickStormBringer, and @yqrashawn)

___
*[packages/db/src/main/cfxjs/db/queries.cljs, line 697 at r1](https://reviewable.io/reviews/conflux-chain/helios/864#-MzyJ8ehB7nhnkmNE6vz:-MzyJ8ehB7nhnkmNE6w-:bqqnck) ([raw file](https://github.com/conflux-chain/helios/blob/02b4f430ee9ffaa2c27c6185c678c22277763b0a/packages/db/src/main/cfxjs/db/queries.cljs#L697)):*
> ```Clojure
>   2. when :address/id and accountId can be identified, return addr with the specified account
>   3. given selected: true, means get the addr of current account under current network, which fullfill 2
>   4. given appId: X, mains get the addr of app's current account under app's current network, which fullfill 2
> ```

'mains' -> `means`
___
*[packages/popup/src/pages/Home/components/AccountList.js, line 153 at r1](https://reviewable.io/reviews/conflux-chain/helios/864#-N-1hSsv6yrNKYXCKbNr:-N-1hSsv6yrNKYXCKbNs:barmzgm) ([raw file](https://github.com/conflux-chain/helios/blob/02b4f430ee9ffaa2c27c6185c678c22277763b0a/packages/popup/src/pages/Home/components/AccountList.js#L153)):*
> ```JavaScript
>             accounts={Object.values(account).filter(({hidden}) => !hidden)}
>             nickname={nickname}
>             currentNetworkId={currentNetworkId}
> ```

should also remove the `currentNetworkId` here

**Comment by yqrashawn** [comment]
@zctocm fixed with new commit

**Review by zctocm — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/864)* status: all files reviewed, 2 unresolved discussions (waiting on @angelia-yuqi-personal, @RickStormBringer, and @yqrashawn)

**Pull request merged**
