### PR TITLE
fix: tx related bug

### PR DESCRIPTION
**Pull request by yqrashawn**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/helios/928)

### CODE REVIEW

**Review by zctocm — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/928)* status: all files reviewed, 1 unresolved discussion (waiting on @yqrashawn)

___
*[`scripts/build/bg.js` line 42 at r1](https://reviewable.io/reviews/conflux-chain/helios/928#-N0PWvkoD64g2P3Uy853:-N0PWvkp0WF9Ud1TwF27:b-vnzi7o) ([raw file](https://github.com/conflux-chain/helios/blob/1fd44089e236961ab7d51616b1cf948435ae9ef1/scripts/build/bg.js#L42)):*
> ```JavaScript
>   splitting: true,
>   minify: isProd(),
>   sourcemap: isProd() ? true : 'inline',
> ```

Does this mean that will have the sourcemap file in production env?

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2921 [多链测试] 交易在 Etherscan 上显示成功，在 Fluent 里显示失败](https://app.clickup.com/t/3719212/PORTAL-2921)

**Comment by yqrashawn** [comment]
> > Reviewed 5 of 5 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/928)_ status: all files reviewed, 1 unresolved discussion (waiting on @yqrashawn)
> 
> _[`scripts/build/bg.js` line 42 at r1](https://reviewable.io/reviews/conflux-chain/helios/928#-N0PWvkoD64g2P3Uy853:-N0PWvkp0WF9Ud1TwF27:b-vnzi7o) ([raw file](https://github.com/conflux-chain/helios/blob/1fd44089e236961ab7d51616b1cf948435ae9ef1/scripts/build/bg.js#L42)):_
> 
> > ```js
> >   splitting: true,
> >   minify: isProd(),
> >   sourcemap: isProd() ? true : 'inline',
> > ```
> 
> Does this mean that will have the sourcemap file in production env?

yes

**Review by zctocm — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/928)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yqrashawn)

___
*[`scripts/build/bg.js` line 42 at r1](https://reviewable.io/reviews/conflux-chain/helios/928#-N0PWvkoD64g2P3Uy853:-N0Q3uOZ1SeTovZzJ6dX:bb6ywmx) ([raw file](https://github.com/conflux-chain/helios/blob/fbe3c6e850775ac9e3c46c62fe474092e7c26e34/scripts/build/bg.js#L42)):*
<details><summary><i>Previously, yqrashawn (yqrashawn) wrote…</i></summary><blockquote>

yes
</blockquote></details>

LGTM

**Pull request merged**
