### PR TITLE
feat: allow grant app permissions directly from popup

### PR DESCRIPTION
**Pull request by yqrashawn**
PORTAL-967

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/helios/126)

### CODE REVIEW

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-967 unable to auth dapp directly in popup, related to wallet_requestPermissions](https://app.clickup.com/t/3719212/PORTAL-967)

**Comment by yqrashawn** [comment]
PORTAL-968
PORTAL-979

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-978 rpc doc support :catn](https://app.clickup.com/t/3719212/PORTAL-978)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-968 修复 Bug: unable to auth dapp directly in popup, related to wallet_requestPermissions](https://app.clickup.com/t/3719212/PORTAL-968)

**Review by angelia-yuqi-personal — APPROVED** [review]

**Pull request merged**
