### PR TITLE
fix: fix bugs

### PR DESCRIPTION
**Pull request by angelia-yuqi-personal**
1. PORTAL-2225
2. PORTAL-2163
3. PORTAL-1976
4. PORTAL-2150
5. PORTAL-2236
6. PORTAL-2164

This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/helios/471)

### CODE REVIEW

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-1976 已授权的 dapp 请求已锁定的钱包时, 解锁后 popup 应该自动关闭](https://app.clickup.com/t/3719212/PORTAL-1976)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2163 根据拆分的三个 html 来处理页面全局的逻辑](https://app.clickup.com/t/3719212/PORTAL-2163)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2236 在send操作中，send token页面的token图标应该根据token进行改变](https://app.clickup.com/t/3719212/PORTAL-2236)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2225 dapp调起硬件钱包账户发交易，会出现confirm2次，且第二次 to 地址清空的情况](https://app.clickup.com/t/3719212/PORTAL-2225)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2164 [UI] Not connected to current website 时，那个区域的高度与 Connected 的时候不一样](https://app.clickup.com/t/3719212/PORTAL-2164)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2150 硬件钱包发交易等待状态的弹窗文案居中](https://app.clickup.com/t/3719212/PORTAL-2150)

**Review by zctocm — APPROVED** [review]

**Pull request merged**
