### PR TITLE
fix: ui check

### PR DESCRIPTION
**Pull request by angelia-yuqi-personal**
1. PORTAL-2326
2. PORTAL-2329
3. PORTAL-2333
4. PORTAL-2335
5. PORTAL-2336

This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/helios/522)

### CODE REVIEW

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2326 4.隐藏 tokne list hover 效果直到有 token 详情页面再加](https://app.clickup.com/t/3719212/PORTAL-2326)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2329 5. token list icon 距离左边边距 12 px](https://app.clickup.com/t/3719212/PORTAL-2329)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2335 3.选择token 弹窗icon距离左边距 24 px](https://app.clickup.com/t/3719212/PORTAL-2335)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2333 1.balance 文字 与数字右对齐](https://app.clickup.com/t/3719212/PORTAL-2333)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2336 4.右上角当前网络icon 16px](https://app.clickup.com/t/3719212/PORTAL-2336)

**Review by zctocm — APPROVED** [review]

**Pull request merged**
