### PR TITLE
feat: add checksum fn

### PR DESCRIPTION
**Pull request by yqrashawn**
PORTAL-2882

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/helios/884)

### CODE REVIEW

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2882 @cfxjs/accounts 增加校验 checksum 函数](https://app.clickup.com/t/3719212/PORTAL-2882)

**Review by zctocm — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/884)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @yqrashawn and @zctocm)

___
*[packages/account/index.js, line 18 at r1](https://reviewable.io/reviews/conflux-chain/helios/884#-N-Rz-aADL8wTEpNmXii:-N-Rz-aADL8wTEpNmXij:bolbiw1) ([raw file](https://github.com/conflux-chain/helios/blob/1b7c4012cd68fc0a032a680b0a704d3b848be41b/packages/account/index.js#L18)):*
> ```JavaScript
> 
> export const toChecksum = compL(addHexPrefix, toChecksumAddress)
> export const checksum = compL(addHexPrefix, addr => {
> ```

maybe `isChecksum` or `validateChecksum` can help others understand this function better?

**Comment by yqrashawn** [comment]
fixed

**Review by zctocm — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/884)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @zctocm)

___
*[packages/account/index.js, line 18 at r1](https://reviewable.io/reviews/conflux-chain/helios/884#-N-Rz-aADL8wTEpNmXii:-N-S0RsWDBFrnWm0XaCd:bb6ywmx) ([raw file](https://github.com/conflux-chain/helios/blob/1b7c4012cd68fc0a032a680b0a704d3b848be41b/packages/account/index.js#L18)):*
<details><summary><i>Previously, zctocm (Chao Zhou) wrote…</i></summary><blockquote>

maybe `isChecksum` or `validateChecksum` can help others understand this function better?
</blockquote></details>

LGTM

**Pull request merged**
