### PR TITLE
fix: feat and fix for eth support

### PR DESCRIPTION
**Pull request by yqrashawn**
PORTAL-2831

- feat: support optional block ref for eth_call
- fix: return msg of permission methods
- feat: optimize permission system
- fix: pass decimal type to etherjs signTx fn
- feat: support gasLimit as gas in sendTransaction
- feat: support detect err type from eth tx error.message
- feat: make block ref optional in eth_estimateGas
- feat: support and ignore password in personal_sign
- refactor: optimize err msg format
- fix: allow empty arg in net_version eth_chainId

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/helios/865)

### CODE REVIEW

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2831 多链 托管MM 一些问题](https://app.clickup.com/t/3719212/PORTAL-2831)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2833 修复 Bug: 多链 托管MM 一些问题](https://app.clickup.com/t/3719212/PORTAL-2833)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2689 dapp 连接 fluent 这里需要修改需求](https://app.clickup.com/t/3719212/PORTAL-2689)

**Review by zctocm — CHANGES_REQUESTED** [review]
> Reviewed 19 of 20 files at r1, 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/865)* status: 18 of 27 files reviewed, 1 unresolved discussion (waiting on @yqrashawn and @zctocm)

___
*[packages/rpcs/eth_signTransaction/index.js, line 79 at r2](https://reviewable.io/reviews/conflux-chain/helios/865#-N-71jN2EzMVrIAsXXxD:-N-71jN2EzMVrIAsXXxE:b-pu4jo2) ([raw file](https://github.com/conflux-chain/helios/blob/ea6e8e0d386cd9512455d1a1c2c3ceb3bfb9ffc7/packages/rpcs/eth_signTransaction/index.js#L79)):*
> ```JavaScript
>   let {from, gas, type, ...newTx} = {...tx}
>   type = type || '0x0'
>   newTx.type = parseInt(type, 16)
> ```


maybe this value should be a hex string?

**Comment by yqrashawn** [comment]
@zctocm the newTx will be passed to `ethers.js` which requires `type` as `number` https://github.com/ethers-io/ethers.js/blob/7b134bd5c9f07f60b2e38b110268042e10f68174/packages/transactions/src.ts/index.ts#L307

**Review by zctocm — CHANGES_REQUESTED** [review]
> Reviewed 1 of 20 files at r1, 1 of 1 files at r2, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/865)* status: all files reviewed, 4 unresolved discussions (waiting on @yqrashawn)

___
*[packages/rpcs/cfx_chainId/index.js, line 37 at r6](https://reviewable.io/reviews/conflux-chain/helios/865#-N-7MZPn6UkwDyZ0EdW-:-N-7MZPn6UkwDyZ0EdW0:bi09g3x) ([raw file](https://github.com/conflux-chain/helios/blob/21d59efb90579c3352f06441d9a1f58d0289c5f1/packages/rpcs/cfx_chainId/index.js#L37)):*
> ```JavaScript
>       getOneNetwork({selected: true}).type === 'cfx')
>   ) {
>     return '0xabcdef1234567890'
> ```

why this value? 



_Code quote:_
```JavaScript
0xabcdef1234567890
```
___
*[packages/rpcs/eth_chainId/index.js, line 27 at r6](https://reviewable.io/reviews/conflux-chain/helios/865#-N-7N7SP8P0r1dz-pla9:-N-7N7SP8P0r1dz-plaA:bebu4dv) ([raw file](https://github.com/conflux-chain/helios/blob/21d59efb90579c3352f06441d9a1f58d0289c5f1/packages/rpcs/eth_chainId/index.js#L27)):*
> ```JavaScript
>       getOneNetwork({selected: true}).type === 'cfx')
>   ) {
>     return '0xabcdef1234567890'
> ```

why this value?
___
*[packages/rpcs/net_version/index.js, line 32 at r6](https://reviewable.io/reviews/conflux-chain/helios/865#-N-7NbJiEpAskiUD1SLj:-N-7NbJiEpAskiUD1SLk:bebu4dv) ([raw file](https://github.com/conflux-chain/helios/blob/21d59efb90579c3352f06441d9a1f58d0289c5f1/packages/rpcs/net_version/index.js#L32)):*
> ```JavaScript
> }) => {
>   if (_inpage && app && type !== getOneNetwork({selected: true}).type) {
>     return 12379813812177893000
> ```

why this value?

**Comment by yqrashawn** [comment]
The idea is to allow calling `eth_chainId` on cfx network and return an impossible chainId when the dapp is asking on a different type of network (different with wallet's current selected network), so that dapp will call the `wallet_switchXXXChain`.

**Comment by zctocm** [comment]
> 



> The idea is to allow calling `eth_chainId` on cfx network and return an impossible chainId when the dapp is asking on a different type of network (different with wallet's current selected network), so that dapp will call the `wallet_switchXXXChain`.

Ok , the limit of `chainId` is the limit of `BigInt`,So you specify a value that exceeds the `BigInt` limit?

**Comment by yqrashawn** [comment]
> > 
> 
> > The idea is to allow calling `eth_chainId` on cfx network and return an impossible chainId when the dapp is asking on a different type of network (different with wallet's current selected network), so that dapp will call the `wallet_switchXXXChain`.
> 
> Ok , the limit of `chainId` is the limit of `BigInt`,So you specify a value that exceeds the `BigInt` limit?

I don't think there's a upper limit for chainId. Even so, I'm ok to change it to Number.MAX_SAFE_INTEGER.

**Comment by zctocm** [comment]
> > > 
> > 
> > 
> > > The idea is to allow calling `eth_chainId` on cfx network and return an impossible chainId when the dapp is asking on a different type of network (different with wallet's current selected network), so that dapp will call the `wallet_switchXXXChain`.
> > 
> > 
> > Ok , the limit of `chainId` is the limit of `BigInt`,So you specify a value that exceeds the `BigInt` limit?
> 
> I don't think there's a upper limit for chainId. Even so, I'm ok to change it to Number.MAX_SAFE_INTEGER.

https://github.com/ethereum/go-ethereum/blob/6d6a5a93370371a33fb815d7ae47b60c7021c86a/params/config.go#L34
https://stackoverflow.com/questions/17564335/golang-math-big-what-is-the-max-value-of-big-int

**Comment by yqrashawn** [comment]
@zctocm I've changed it to `Number.MAX_SAFE_INTEGER`

**Review by zctocm — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/865)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yqrashawn)

___
*[packages/rpcs/cfx_chainId/index.js, line 37 at r6](https://reviewable.io/reviews/conflux-chain/helios/865#-N-7MZPn6UkwDyZ0EdW-:-N-LCtZq5HZEZ-6yWDmr:bb6ywmx) ([raw file](https://github.com/conflux-chain/helios/blob/d1a790c1b97d4f73225edaf7b243bd604962b038/packages/rpcs/cfx_chainId/index.js#L37)):*
<details><summary><i>Previously, zctocm (Chao Zhou) wrote…</i></summary><blockquote>

why this value? 
</blockquote></details>

LGTM
___
*[packages/rpcs/eth_chainId/index.js, line 27 at r6](https://reviewable.io/reviews/conflux-chain/helios/865#-N-7N7SP8P0r1dz-pla9:-N-LCxUN8EKbcrLFRK5Q:b-85i64v) ([raw file](https://github.com/conflux-chain/helios/blob/d1a790c1b97d4f73225edaf7b243bd604962b038/packages/rpcs/eth_chainId/index.js#L27)):*
<details><summary><i>Previously, zctocm (Chao Zhou) wrote…</i></summary><blockquote>

why this value?
</blockquote></details>

LGTM
___
*[packages/rpcs/eth_signTransaction/index.js, line 79 at r2](https://reviewable.io/reviews/conflux-chain/helios/865#-N-71jN2EzMVrIAsXXxD:-N-LD-OsDeb89qjxfrfr:bb6ywmx) ([raw file](https://github.com/conflux-chain/helios/blob/ea6e8e0d386cd9512455d1a1c2c3ceb3bfb9ffc7/packages/rpcs/eth_signTransaction/index.js#L79)):*
<details><summary><i>Previously, zctocm (Chao Zhou) wrote…</i></summary><blockquote>


maybe this value should be a hex string?
</blockquote></details>

LGTM
___
*[packages/rpcs/net_version/index.js, line 32 at r6](https://reviewable.io/reviews/conflux-chain/helios/865#-N-7NbJiEpAskiUD1SLj:-N-LD14n7qGH0PmwalQE:bb6ywmx) ([raw file](https://github.com/conflux-chain/helios/blob/d1a790c1b97d4f73225edaf7b243bd604962b038/packages/rpcs/net_version/index.js#L32)):*
<details><summary><i>Previously, zctocm (Chao Zhou) wrote…</i></summary><blockquote>

why this value?
</blockquote></details>

LGTM

**Pull request merged**
