### PR TITLE
fix: refetch balance won't return error

### PR DESCRIPTION
**Pull request by yqrashawn**
PORTAL-2504

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/helios/643)

### CODE REVIEW

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-2504 当某个网络没有 cfx_getBalance 方法时, 即使钱包没有切换到该网络, 也会报错, 导致钱包无法使用](https://app.clickup.com/t/3719212/PORTAL-2504)

**Review by zctocm — APPROVED** [review]

**Comment by yqrashawn** [comment]
@Mergifyio refresh

**Comment by yqrashawn** [comment]
@Mergifyio refresh

**Comment by yqrashawn** [comment]
@Mergifyio refresh

**Pull request merged**
