### PR TITLE
feat: ledger support for eth network

### PR DESCRIPTION
**Pull request by yqrashawn**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/helios/878)

### CODE REVIEW

**Review by zctocm — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/878)* status: all files reviewed, 1 unresolved discussion (waiting on @yqrashawn)

___
*[packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/index.js, line 140 at r1](https://reviewable.io/reviews/conflux-chain/helios/878#-N-MJ7-b19y44AkIjcjZ:-N-MJ7-b19y44AkIjcj_:b2qwi8) ([raw file](https://github.com/conflux-chain/helios/blob/7086fce29f44e4730bc1dd49399fe4344b933dd4/packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/index.js#L140)):*
> ```JavaScript
>       (acc, {eid, netId, type}, idx) =>
>         address.reduce((acc, {address, nickname}, jdx) => {
>           // hw-vaults.cfxOnly are set explicitly the first time credating the group
> ```

`credating` -> `creating`



_Code quote:_
```JavaScript
hw-vaults.cfxOnly are set explicitly the first time credating the group
```

**Comment by yqrashawn** [comment]
@zctocm fixed in the latest commit

**Review by zctocm — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/878)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @yqrashawn and @zctocm)

___
*[packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/index.js, line 140 at r1](https://reviewable.io/reviews/conflux-chain/helios/878#-N-MJ7-b19y44AkIjcjZ:-N-MQmgr85PXbycXGQDP:b-kdg83g) ([raw file](https://github.com/conflux-chain/helios/blob/7086fce29f44e4730bc1dd49399fe4344b933dd4/packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/index.js#L140)):*
<details><summary><i>Previously, zctocm (Chao Zhou) wrote…</i></summary><blockquote>

`credating` -> `creating`
</blockquote></details>

`crating`?

**Comment by yqrashawn** [comment]
@zctocm fixed

**Review by zctocm — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/878)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @zctocm)

___
*[packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/index.js, line 140 at r1](https://reviewable.io/reviews/conflux-chain/helios/878#-N-MJ7-b19y44AkIjcjZ:-N-MfX456eNxzH7H3BKv:bb6ywmx) ([raw file](https://github.com/conflux-chain/helios/blob/7086fce29f44e4730bc1dd49399fe4344b933dd4/packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/index.js#L140)):*
<details><summary><i>Previously, zctocm (Chao Zhou) wrote…</i></summary><blockquote>

`crating`?
</blockquote></details>

LGTM

**Pull request merged**
