### PR TITLE
fix: spec, error handling in detectNetworkType

### PR DESCRIPTION
**Pull request by yqrashawn**
PORTAL-1302
PORTAL-1275

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/helios/203)

### CODE REVIEW

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-1302 修复 Bug: 接口wallet_refetchBalance的参数输入任何符合type类型值都返回执行成功的结果](https://app.clickup.com/t/3719212/PORTAL-1302)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-1275 接口wallet_detectNetworkType没有处理当url不对的情况](https://app.clickup.com/t/3719212/PORTAL-1275)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-1342 修复 Bug: walletdb_addTokenList balance 返回值为 数组。期望返回当前地址 当前网络的balance.](https://app.clickup.com/t/3719212/PORTAL-1342)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-1336 修复 Bug: home 页面 添加token。添加完之后。walletdb_addTokenList 接口返回的数据 没有更新 added 字段的状态](https://app.clickup.com/t/3719212/PORTAL-1336)

**Review by RickStormBringer — APPROVED** [review]

**Review by RickStormBringer — APPROVED** [review]

**Review by angelia-yuqi-personal — APPROVED** [review]

**Pull request merged**
