### PR TITLE
feat: refactor db

### PR DESCRIPTION
**Pull request by yqrashawn**
BREAKING CHANGE

1. network/address -> address/network
1. token/address -> token/network
1. add same address to single network will throw
1. ~~accountGroup/account -> account/accountGroup~~
1. remove address/base32 address/cfxHex, add address/value, address/value is address value under address/network
1. remove address/vault address/index (same as account/index)
1. tx/payload -> tx/txPayload
1. tx/extra -> tx/txExtra
1. add pull functions for graph query
1. rename wallet_getExplorerUrl to wallet_getBlockchainExplorerUrl
1. fix bugs in provider rpc method
1. Remove checks of duplicate account nickname in create/update account
1. RPC request from dapp will automatically use :app/currentNetwork 
1. Delete app auth will posts accountsChanged event to dapp with zero accounts
1. Set detect network type timeout to 5 sec
1. Add query function for group,account, address, token
1. Fix a bug that too stale nonce error results in permanent pending tax status
1. Fix a bug that tx with data and built in to address cause tx info error
1. add wallet_getFluentMetadata rpc

---
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/helios/290)

### CODE REVIEW

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-1633 新建account的时候，account name如果重复，没有错误提示也没有任何响应](https://app.clickup.com/t/3719212/PORTAL-1633)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-1630 refactor db](https://app.clickup.com/t/3719212/PORTAL-1630)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-1648 nonce不对的send操作,在history的列表里会一直处于pending状态](https://app.clickup.com/t/3719212/PORTAL-1648)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-1647 nonce设置不对的send操作，在history中会一直处于pending](https://app.clickup.com/t/3719212/PORTAL-1647)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-1586 fluentwallet断开moon链接后，moon仍显示链接](https://app.clickup.com/t/3719212/PORTAL-1586)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-1577 接口cfx_sendTransaction在nonce不正确的情况下(小于当前nonce)没有返回信息](https://app.clickup.com/t/3719212/PORTAL-1577)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-1589 dapp approve 无法解析token 字段是空。](https://app.clickup.com/t/3719212/PORTAL-1589)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-1666 修复 Bug: dapp approve 无法解析token 字段是空。](https://app.clickup.com/t/3719212/PORTAL-1666)

**Comment by angelia-yuqi-personal** [comment]
> BREAKING CHANGE
> 
> 1. network/address -> address/network
> 2. token/address -> token/network
> 3. add same address to single network will throw
> 4. accountGroup/account -> account/accountGroup
> 5. remove address/base32 address/cfxHex, add address/value, address/value is address value under address/network
> 6. remove address/vault address/index (same as account/index)
> 7. tx/payload -> tx/txPayload
> 8. tx/extra -> tx/txExtra
> 9. add pull functions for graph query
> 10. rename wallet_getExplorerUrl to wallet_getBlockchainExplorerUrl
> 11. fix bugs in provider rpc method
> 
> This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/helios/290)

Is there any update for the breaking change detail?

**Comment by yqrashawn** [comment]
@angelia-yuqi-personal I've updated the top comments for latest commits

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-1646 发修改过Gas fee的普通交易，History中查看交易一直是Pending状态](https://app.clickup.com/t/3719212/PORTAL-1646)

**Comment by angelia-yuqi-personal** [comment]
Task linked: [PORTAL-1536 get fluent version rpc](https://app.clickup.com/t/3719212/PORTAL-1536)

**Review by angelia-yuqi-personal — APPROVED** [review]

**Pull request merged**
